server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/unzilemedet/ConfigServerGit.git
          default-label: main
          skip-ssl-validation: true
          username: unzilemedet
          password: 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