server:
  port: 8060

spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: HR-ManagementDB
      username: JavaUser
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}


#rabbitmq:
#  user-exchange: user-exchange
#  personnelPasswordKey: personnel-password-key
#  queuePersonnelPassword: queue-personnel-password
